name: Build APK for ATM-Notifier-App

on:
  push:
    branches:
      - main  # أو الفرع الذي تستخدمه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: تحقق من الكود
      - name: Checkout repository
        uses: actions/checkout@v2

      # الخطوة 2: إعداد JDK 17 مع توزيع Temurin
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # الخطوة 3: إعداد Android SDK باستخدام setup-android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-version: '30'

      # الخطوة 4: تثبيت Gradle باستخدام SDKMAN
      - name: Install Gradle
        run: |
          curl -s https://get.sdkman.io | bash  # تثبيت SDKMAN
          source $HOME/.sdkman/bin/sdkman-init.sh
          sdk install gradle  # تثبيت Gradle باستخدام SDKMAN

      # الخطوة 5: بناء APK باستخدام Gradle (مع استخدام Gradle Wrapper إذا كان موجودًا)
      - name: Build APK using Gradle
        run: ./gradlew assembleDebug  # استخدام Gradle Wrapper إذا كان موجودًا
        continue-on-error: true  # استمر في تنفيذ البناء حتى إذا فشل في العثور على ملف Gradle Wrapper

      # الخطوة 6: رفع APK كـ Artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: atm-notifier-apk
          path: app/build/outputs/apk/debug/app-debug.apk
