name: Build APK for ATM-Notifier-App

on:
  push:
    branches:
      - main  # يمكن تغييرها إلى الفرع الذي تستخدمه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: تحقق من الكود
      - name: Checkout repository
        uses: actions/checkout@v2

      # الخطوة 2: إعداد JDK 17 مع توزيع Temurin
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # الخطوة 3: إعداد Android SDK باستخدام setup-android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-version: '30'

      # الخطوة 4: تثبيت Gradle باستخدام أداة apt-get
      - name: Install Gradle
        run: |
          sudo apt-get install -y gradle  # تثبيت Gradle مباشرة باستخدام apt-get

      # الخطوة 5: عرض قائمة المهام المتاحة
      - name: List available Gradle tasks
        run: gradle tasks

      # الخطوة 6: بناء APK
      - name: Build APK
        run: gradle assembleRelease  # استخدم المهمة المناسبة حسب ما تم العثور عليه

      # الخطوة 7: التأكد من أن الـ APK تم إنشاؤه
      - name: List APK directory
        run: ls -l app/build/outputs/apk/release/

      # الخطوة 8: رفع APK كـ artifact
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: atm-notifier-apk
          path: app/build/outputs/apk/release/app-release.apk
