name: Build APK for ATM-Notifier-App

on:
  push:
    branches:
      - main  # يمكن تغييرها إلى الفرع الذي تستخدمه

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # الخطوة 1: تحقق من الكود
      - name: Checkout repository
        uses: actions/checkout@v2

      # الخطوة 2: إعداد JDK 17 مع توزيع Temurin
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # استخدام توزيعة Temurin

      # الخطوة 3: إعداد Android SDK باستخدام setup-android
      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-version: '30'  # التأكد من استخدام الإصدار الصحيح من Android SDK

      # الخطوة 4: تثبيت Gradle باستخدام SDKMAN
      - name: Install Gradle
        run: |
          sdk install gradle  # استخدام SDKMAN لتثبيت Gradle

      # الخطوة 5: بناء APK
      - name: Build APK
        run: gradle assembleRelease  # بناء ملف APK للإصدار

      # الخطوة 6: رفع APK كـ artifact باستخدام الإصدار v4
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: atm-notifier-apk
          path: app/build/outputs/apk/release/app-release.apk
